#install.packages('sna')
#install.packages('rsq')
#install.packages('ergm')
#install.packages('goft')
#install.packages('MASS')
#install.packages('igraph')
#install.packages('statnet')
#install.packages('network')
#install.packages('survival')
#install.packages('intergraph')
#install.packages('fitdistrplus')

library(sna)
library(rsq)
library(ergm)
library(goft)
library(MASS)
library(igraph)
library(statnet)
library(network)
library(survival)
library(intergraph)
library(fitdistrplus)

setwd("C:/Users/Liad/Desktop/SNA_Exam_2018/forStudents")
#part_1
network1_sna<-read.paj("ia-email-EU.net")
network1_igraph<-asIgraph(network1_sna)
is.directed(network1_igraph)
#part_2
nodes<-network.size(network1_sna)
dens<-gden(network1_sna)
dens
#randnet1<-rgraph(n=nodes,m=1,tprob=dens)
#randNet<-rgnm(10,100,20,diag=FALSE,mode="digraph")
network1_rand_sna<-read.paj("ia-email-EU-random.net")
network1_rand_igraph<-asIgraph(network1_rand_sna)
nodes_rand<-network.size(network1_rand)
dens_rand<-gden(network1_rand)
dens==dens_rand
deg<-degree.distribution(network1_igraph)
plot(deg)
deg_rand<-degree.distribution(network1_rand_igraph)
plot(deg_rand)
#part_3
t.test(deg,deg_rand)
#part_4
glist <- replicate(100, erdos.renyi.game(vcount(network1_igraph), ecount(network1_igraph), type="gnm", directed=FALSE),simplify=FALSE)
transitivity(network1_igraph)
average.path.length(network1_igraph)
stats <- sapply(glist, function(g) c(clustering=transitivity(g), distances=average.path.length(g)))
stats <- as.data.frame(t(stats))
CC.ratio<-transitivity(network1_igraph)/colMeans(stats)[1]
CPL.ratio<-average.path.length(network1_igraph)/colMeans(stats)[2]
CC.ratio
CPL.ratio
#part_5
plot(sort(degree(network1_sna)))
igraph::fit_power_law(sort(degree(network1_sna)))
rsq::rsq(sort(degree(network1_sna)))
sfn<-barabasi.game(vcount(network1_igraph),power=1)
summary(sort(degree(network1_sna)))